// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: supervisor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_supervisor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XretractorRunning bool                   `protobuf:"varint,2,opt,name=xretractor_running,json=xretractorRunning,proto3" json:"xretractor_running,omitempty"`
	QueryFile         string                 `protobuf:"bytes,3,opt,name=query_file,json=queryFile,proto3" json:"query_file,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_supervisor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetXretractorRunning() bool {
	if x != nil {
		return x.XretractorRunning
	}
	return false
}

func (x *HealthResponse) GetQueryFile() string {
	if x != nil {
		return x.QueryFile
	}
	return ""
}

type TextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextResponse) Reset() {
	*x = TextResponse{}
	mi := &file_supervisor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResponse) ProtoMessage() {}

func (x *TextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResponse.ProtoReflect.Descriptor instead.
func (*TextResponse) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{2}
}

func (x *TextResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TextResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_supervisor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *StatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadRequest) Reset() {
	*x = ReloadRequest{}
	mi := &file_supervisor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRequest) ProtoMessage() {}

func (x *ReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRequest.ProtoReflect.Descriptor instead.
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{4}
}

func (x *ReloadRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type UploadRQLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRQLRequest) Reset() {
	*x = UploadRQLRequest{}
	mi := &file_supervisor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRQLRequest) ProtoMessage() {}

func (x *UploadRQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRQLRequest.ProtoReflect.Descriptor instead.
func (*UploadRQLRequest) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{5}
}

func (x *UploadRQLRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadRQLRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type AdhocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdhocRequest) Reset() {
	*x = AdhocRequest{}
	mi := &file_supervisor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdhocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdhocRequest) ProtoMessage() {}

func (x *AdhocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdhocRequest.ProtoReflect.Descriptor instead.
func (*AdhocRequest) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{6}
}

func (x *AdhocRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type QueryTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        bool                   `protobuf:"varint,1,opt,name=fields,proto3" json:"fields,omitempty"`
	Tags          bool                   `protobuf:"varint,2,opt,name=tags,proto3" json:"tags,omitempty"`
	Streamprogs   bool                   `protobuf:"varint,3,opt,name=streamprogs,proto3" json:"streamprogs,omitempty"`
	Rules         bool                   `protobuf:"varint,4,opt,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTreeRequest) Reset() {
	*x = QueryTreeRequest{}
	mi := &file_supervisor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTreeRequest) ProtoMessage() {}

func (x *QueryTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTreeRequest.ProtoReflect.Descriptor instead.
func (*QueryTreeRequest) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{7}
}

func (x *QueryTreeRequest) GetFields() bool {
	if x != nil {
		return x.Fields
	}
	return false
}

func (x *QueryTreeRequest) GetTags() bool {
	if x != nil {
		return x.Tags
	}
	return false
}

func (x *QueryTreeRequest) GetStreamprogs() bool {
	if x != nil {
		return x.Streamprogs
	}
	return false
}

func (x *QueryTreeRequest) GetRules() bool {
	if x != nil {
		return x.Rules
	}
	return false
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_supervisor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{8}
}

func (x *StreamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DataChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataChunk) Reset() {
	*x = DataChunk{}
	mi := &file_supervisor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChunk) ProtoMessage() {}

func (x *DataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChunk.ProtoReflect.Descriptor instead.
func (*DataChunk) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{9}
}

func (x *DataChunk) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type FieldInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldInfo) Reset() {
	*x = FieldInfo{}
	mi := &file_supervisor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldInfo) ProtoMessage() {}

func (x *FieldInfo) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldInfo.ProtoReflect.Descriptor instead.
func (*FieldInfo) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{10}
}

func (x *FieldInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*FieldInfo           `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaResponse) Reset() {
	*x = SchemaResponse{}
	mi := &file_supervisor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaResponse) ProtoMessage() {}

func (x *SchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaResponse.ProtoReflect.Descriptor instead.
func (*SchemaResponse) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{11}
}

func (x *SchemaResponse) GetFields() []*FieldInfo {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SchemaResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Process       string                 `protobuf:"bytes,2,opt,name=process,proto3" json:"process,omitempty"`
	Line          string                 `protobuf:"bytes,3,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_supervisor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{12}
}

func (x *LogEntry) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *LogEntry) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

func (x *LogEntry) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type LogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_supervisor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{13}
}

func (x *LogsResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_supervisor_proto protoreflect.FileDescriptor

const file_supervisor_proto_rawDesc = "" +
	"\n" +
	"\x10supervisor.proto\x12\rsupervisor.v1\"\a\n" +
	"\x05Empty\"v\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12-\n" +
	"\x12xretractor_running\x18\x02 \x01(\bR\x11xretractorRunning\x12\x1d\n" +
	"\n" +
	"query_file\x18\x03 \x01(\tR\tqueryFile\"<\n" +
	"\fTextResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"V\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"#\n" +
	"\rReloadRequest\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\"@\n" +
	"\x10UploadRQLRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"$\n" +
	"\fAdhocRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"v\n" +
	"\x10QueryTreeRequest\x12\x16\n" +
	"\x06fields\x18\x01 \x01(\bR\x06fields\x12\x12\n" +
	"\x04tags\x18\x02 \x01(\bR\x04tags\x12 \n" +
	"\vstreamprogs\x18\x03 \x01(\bR\vstreamprogs\x12\x14\n" +
	"\x05rules\x18\x04 \x01(\bR\x05rules\"#\n" +
	"\rStreamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1f\n" +
	"\tDataChunk\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\"3\n" +
	"\tFieldInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"X\n" +
	"\x0eSchemaResponse\x120\n" +
	"\x06fields\x18\x01 \x03(\v2\x18.supervisor.v1.FieldInfoR\x06fields\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"L\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12\x18\n" +
	"\aprocess\x18\x02 \x01(\tR\aprocess\x12\x12\n" +
	"\x04line\x18\x03 \x01(\tR\x04line\"A\n" +
	"\fLogsResponse\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.supervisor.v1.LogEntryR\aentries2\x91\x06\n" +
	"\n" +
	"Supervisor\x12=\n" +
	"\x06Health\x12\x14.supervisor.v1.Empty\x1a\x1d.supervisor.v1.HealthResponse\x12@\n" +
	"\vListQueries\x12\x14.supervisor.v1.Empty\x1a\x1b.supervisor.v1.TextResponse\x12L\n" +
	"\fGetQueryTree\x12\x1f.supervisor.v1.QueryTreeRequest\x1a\x1b.supervisor.v1.TextResponse\x12E\n" +
	"\x06Reload\x12\x1c.supervisor.v1.ReloadRequest\x1a\x1d.supervisor.v1.StatusResponse\x12K\n" +
	"\tUploadRQL\x12\x1f.supervisor.v1.UploadRQLRequest\x1a\x1d.supervisor.v1.StatusResponse\x12C\n" +
	"\x05Adhoc\x12\x1b.supervisor.v1.AdhocRequest\x1a\x1d.supervisor.v1.StatusResponse\x12D\n" +
	"\rStopRetractor\x12\x14.supervisor.v1.Empty\x1a\x1d.supervisor.v1.StatusResponse\x12?\n" +
	"\bShutdown\x12\x14.supervisor.v1.Empty\x1a\x1d.supervisor.v1.StatusResponse\x12<\n" +
	"\aGetLogs\x12\x14.supervisor.v1.Empty\x1a\x1b.supervisor.v1.LogsResponse\x12F\n" +
	"\n" +
	"StreamData\x12\x1c.supervisor.v1.StreamRequest\x1a\x18.supervisor.v1.DataChunk0\x01\x12N\n" +
	"\x0fGetStreamSchema\x12\x1c.supervisor.v1.StreamRequest\x1a\x1d.supervisor.v1.SchemaResponseB\x10Z\x0ersupervisor/pbb\x06proto3"

var (
	file_supervisor_proto_rawDescOnce sync.Once
	file_supervisor_proto_rawDescData []byte
)

func file_supervisor_proto_rawDescGZIP() []byte {
	file_supervisor_proto_rawDescOnce.Do(func() {
		file_supervisor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_supervisor_proto_rawDesc), len(file_supervisor_proto_rawDesc)))
	})
	return file_supervisor_proto_rawDescData
}

var file_supervisor_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_supervisor_proto_goTypes = []any{
	(*Empty)(nil),            // 0: supervisor.v1.Empty
	(*HealthResponse)(nil),   // 1: supervisor.v1.HealthResponse
	(*TextResponse)(nil),     // 2: supervisor.v1.TextResponse
	(*StatusResponse)(nil),   // 3: supervisor.v1.StatusResponse
	(*ReloadRequest)(nil),    // 4: supervisor.v1.ReloadRequest
	(*UploadRQLRequest)(nil), // 5: supervisor.v1.UploadRQLRequest
	(*AdhocRequest)(nil),     // 6: supervisor.v1.AdhocRequest
	(*QueryTreeRequest)(nil), // 7: supervisor.v1.QueryTreeRequest
	(*StreamRequest)(nil),    // 8: supervisor.v1.StreamRequest
	(*DataChunk)(nil),        // 9: supervisor.v1.DataChunk
	(*FieldInfo)(nil),        // 10: supervisor.v1.FieldInfo
	(*SchemaResponse)(nil),   // 11: supervisor.v1.SchemaResponse
	(*LogEntry)(nil),         // 12: supervisor.v1.LogEntry
	(*LogsResponse)(nil),     // 13: supervisor.v1.LogsResponse
}
var file_supervisor_proto_depIdxs = []int32{
	10, // 0: supervisor.v1.SchemaResponse.fields:type_name -> supervisor.v1.FieldInfo
	12, // 1: supervisor.v1.LogsResponse.entries:type_name -> supervisor.v1.LogEntry
	0,  // 2: supervisor.v1.Supervisor.Health:input_type -> supervisor.v1.Empty
	0,  // 3: supervisor.v1.Supervisor.ListQueries:input_type -> supervisor.v1.Empty
	7,  // 4: supervisor.v1.Supervisor.GetQueryTree:input_type -> supervisor.v1.QueryTreeRequest
	4,  // 5: supervisor.v1.Supervisor.Reload:input_type -> supervisor.v1.ReloadRequest
	5,  // 6: supervisor.v1.Supervisor.UploadRQL:input_type -> supervisor.v1.UploadRQLRequest
	6,  // 7: supervisor.v1.Supervisor.Adhoc:input_type -> supervisor.v1.AdhocRequest
	0,  // 8: supervisor.v1.Supervisor.StopRetractor:input_type -> supervisor.v1.Empty
	0,  // 9: supervisor.v1.Supervisor.Shutdown:input_type -> supervisor.v1.Empty
	0,  // 10: supervisor.v1.Supervisor.GetLogs:input_type -> supervisor.v1.Empty
	8,  // 11: supervisor.v1.Supervisor.StreamData:input_type -> supervisor.v1.StreamRequest
	8,  // 12: supervisor.v1.Supervisor.GetStreamSchema:input_type -> supervisor.v1.StreamRequest
	1,  // 13: supervisor.v1.Supervisor.Health:output_type -> supervisor.v1.HealthResponse
	2,  // 14: supervisor.v1.Supervisor.ListQueries:output_type -> supervisor.v1.TextResponse
	2,  // 15: supervisor.v1.Supervisor.GetQueryTree:output_type -> supervisor.v1.TextResponse
	3,  // 16: supervisor.v1.Supervisor.Reload:output_type -> supervisor.v1.StatusResponse
	3,  // 17: supervisor.v1.Supervisor.UploadRQL:output_type -> supervisor.v1.StatusResponse
	3,  // 18: supervisor.v1.Supervisor.Adhoc:output_type -> supervisor.v1.StatusResponse
	3,  // 19: supervisor.v1.Supervisor.StopRetractor:output_type -> supervisor.v1.StatusResponse
	3,  // 20: supervisor.v1.Supervisor.Shutdown:output_type -> supervisor.v1.StatusResponse
	13, // 21: supervisor.v1.Supervisor.GetLogs:output_type -> supervisor.v1.LogsResponse
	9,  // 22: supervisor.v1.Supervisor.StreamData:output_type -> supervisor.v1.DataChunk
	11, // 23: supervisor.v1.Supervisor.GetStreamSchema:output_type -> supervisor.v1.SchemaResponse
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_supervisor_proto_init() }
func file_supervisor_proto_init() {
	if File_supervisor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_supervisor_proto_rawDesc), len(file_supervisor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_supervisor_proto_goTypes,
		DependencyIndexes: file_supervisor_proto_depIdxs,
		MessageInfos:      file_supervisor_proto_msgTypes,
	}.Build()
	File_supervisor_proto = out.File
	file_supervisor_proto_goTypes = nil
	file_supervisor_proto_depIdxs = nil
}
