@startuml

title Processing data sequence \n for Device one-time read-only data source (OTRO)
[*] --> Storage

state Storage as "One-Time Data Source accessor State Machine" {

  state ZeroStep as "ZERO Step" {
    [*] --> Empty
    state Empty : no data
  }

  state MainLoop as "Main Processing Loop" {
    state Armed : data in chamber_ ready
    state Flux : chamber_ moved to payload
    Flux --> Armed : fire chamber_ data into c-buf
    Armed --> Flux : read data from source
  }

  Empty -> Armed : first read from source

  }

@enduml