@startuml

title Processing data sequence \n for Device one-stop-read
[*] --> Storage

state Storage as "Storage State Machine" {

  state ZeroStep as "ZERO Step" {
    [*] --> Empty
    state Empty : no data
  }

  state MainLoop as "Main Processing Loop" {
    state Armed : data in chamber ready
    state Flux : chamber moved to payload
    state Lock : data in circural buffer 
    Flux --> Armed 
    Armed --> Lock
    Lock --> Flux
  }

  Empty-> Lock


  note right of Flux
  read data from data source 
  data placed in chamber
  end note
  
  note right of Armed
  new readed data waits in chamber
  read from storage gets data from circural buffer
  end note
  
  note right of Lock
  data moved from chamber into circual buffer
  read from storage gets from circural buffer
  end note

  note left of Empty
  chamber & payload is empty 
  no data has been readed from source
  end note

  }

@enduml