# _Test description_
# testing text data source as stream input
# reads data_souce.txt file and gets
# sequential results in loop from txt file
noprompt
dropfile { data_source.desc }
open data_source { INTEGER dane STRING name[5] REF "data_source.txt" TYPE TEXTSOURCE }
desc
size
read 0
printt
read 0
printt
read 0
printt
read 0
printt
cap 3
read 0
read 0
read 0
echo rlist 3
rlist 3
echo rlist 3
rlist 3
echo rlist 3
rlist 3
echo freeze - rlist 3
freeze
rlist 3
echo freeze - rlist 3
rlist 3
echo unfreeze - rlist 3
unfreeze
rlist 3
dropfile { data_source.desc }
quit
