@startuml

class Descriptor {
    {method} append
    {method} operator|
    {method} operator=
    {method} getSizeInBytes
    {method} position
    {method} len
    {method} offset
    {method} type
    {method} toString
    {method} cast
    {method} operator<<
    {method} operator>>
}

class genericBinaryFileAccessor {
    {field} fileNameStr
    {field} fd
}


class posixBinaryFileAccessor {
    {field} fileNameStr
}

class posixPrmBinaryFileAccessor {
    {field} fileNameStr
    {field} fd
}

class binaryDeviceAccessor {
    {field} fileNameStr
    {field} fd
}

class textSourceAccessor {
    {field} fileNameStr
    {field} fd
    {field} fctrl
}

FileAccessorInterface ()-- binaryDeviceAccessor
FileAccessorInterface ()-- posixPrmBinaryFileAccessor
FileAccessorInterface ()-- posixBinaryFileAccessor
FileAccessorInterface ()-- genericBinaryFileAccessor
FileAccessorInterface ()-- textSourceAccessor

interface FileAccessorInterface {
    {method} read
    {method} write
    {method} fileName
    {method} fctrl
}

class payload {
    {field} descriptor

    {method} getDescriptor
    {method} get
    {method} setItem
    {method} getItem
    {method} setHex
    {method} operator>>
    {method} operator<<
}

class storageAccessor {
    {field} accessor
    {field} descriptor
    {field} reverse
    {field} recordsCount
    {field} dataFileStatus
    {field} filename

    {method} attachDescriptor
    {method} read
    {method} write
    {method} getDescriptor
    {method} setReverse
    {method} setRemoveOnExit
    {method} getRecordsCount
}

enum rdb::descFld {
    STRING
    UINT
    BYTE
    INTEGER
    FLOAT
    DOUBLE
    REF
    TYPE
}

genericBinaryFileAccessor --* storageAccessor
posixBinaryFileAccessor --* storageAccessor
posixPrmBinaryFileAccessor --* storageAccessor
binaryDeviceAccessor --* storageAccessor
textSourceAccessor --* storageAccessor

Descriptor --* storageAccessor


Descriptor --- rdb::descFld

payload --* storageAccessor

@enduml