@startuml

class Descriptor {
    {field} fieldNames

    {method} append
    {method} operator|
    {method} operator=
    {method} getSizeInBytes
    {method} position
    {method} len
    {method} offset
    {method} type
    {method} toString
    {method} cast
    {method} operator<<
    {method} operator>>
}

class genericBinaryFileAccessor {
    {field} fileNameStr
}


class posixBinaryFileAccessor {
    {field} fileNameStr
}

class posixPrmBinaryFileAccessor {
    {field} fileNameStr
    {field} fd
}


interface FileAccessorInterface {
    {method} read
    {method} write
    {method} fileName
}

class payLoadAccessor {
    {field} descriptor
    {field} ptr
    {field} hexFormat

    {method} getDescriptor
    {method} getPayloadPtr
    {method} setItem
    {method} getItem
    {method} operator>>
    {method} operator<<
}

class DataStorageAccessor {
    {field} accessor
    {field} descriptor
    {field} reverse
    {field} recordsCount
    {field} dataFileStatus
    {field} filename

    {method} createDescriptor
    {method} get
    {method} put
    {method} getDescriptor
    {method} setReverse
    {method} setRemoveOnExit
    {method} getRecordsCount
    {method} getStorageFilename
}

enum rdb::eType {
    STRING
    BYTEARRAY
    UINT
    BYTE
    INTEGER
    FLOAT
    DOUBLE
}

FileAccessorInterface --> genericBinaryFileAccessor
FileAccessorInterface --> posixBinaryFileAccessor
FileAccessorInterface --> posixPrmBinaryFileAccessor

genericBinaryFileAccessor --* DataStorageAccessor
posixBinaryFileAccessor --* DataStorageAccessor
posixPrmBinaryFileAccessor --* DataStorageAccessor

Descriptor --* DataStorageAccessor

Descriptor --- rdb::eType

payLoadAccessor --* Descriptor

@enduml