@startuml

class Descriptor {
    {field} fieldNames

    {method} Append
    {method} operator|
    {method} operator=
    {method} getSizeInBytes
    {method} Position
    {method} Len
    {method} Offset
    {method} Type
    {method} ToString
    {method} Cast
    {method} operator<<
    {method} operator>>
}

class genericBinaryFileAccessor {
    {field} fileNameStr
}


class posixBinaryFileAccessor {
    {field} fileNameStr
}

class posixPrmBinaryFileAccessor {
    {field} fileNameStr
    {field} fd
}


interface FileAccessorInterface {
    {method} Read
    {method} Write
    {method} FileName
}

class payLoadAccessor {
    {field} descriptor
    {field} ptr
    {field} hexFormat

    {method} getDescriptor
    {method} getPayloadPtr
    {method} set_item
    {method} get_item
    {method} operator>>
    {method} operator<<
}

class DataStorageAccessor {
    {field} accessor
    {field} descriptor
    {field} reverse
    {field} recordsCount
    {field} dataFileStatus
    {field} filename

    {method} createDescriptor
    {method} Get
    {method} Put
    {method} getDescriptor
    {method} setReverse
    {method} setRemoveOnExit
    {method} getRecordsCount
    {method} getStorageFilename
}

enum rdb::eType {
    STRING
    BYTEARRAY
    UINT
    BYTE
    INTEGER
    FLOAT
    DOUBLE
}

FileAccessorInterface --> genericBinaryFileAccessor
FileAccessorInterface --> posixBinaryFileAccessor
FileAccessorInterface --> posixPrmBinaryFileAccessor

genericBinaryFileAccessor --* DataStorageAccessor
posixBinaryFileAccessor --* DataStorageAccessor
posixPrmBinaryFileAccessor --* DataStorageAccessor

Descriptor --* DataStorageAccessor

Descriptor --- rdb::eType

payLoadAccessor --* Descriptor

@enduml