noprompt
echo SELECT * STREAM signalText0 FROM core1@(1,4)
echo This looks OK
open signalText0
size
descc
list 6
echo SELECT * STREAM signalTextR FROM core1@(1,-4)
echo This looks OK
open signalTextR
size
descc
list 6
echo SELECT * STREAM signalText1 FROM core1@(2,4)
echo This looks OK
open signalText1
size
descc
list 6
echo SELECT * STREAM signalText3 FROM core1@(2,2)
echo This looks OK
open signalText3
size
descc
list 6
echo SELECT * STREAM signalText5 FROM signalText3@(1,1)
echo Investigation here
open signalText5
size
descc
list 6
dropfile { core0.desc core1.desc }
dropfile { signalRow signalRow.desc signalRowR signalRowR.desc }
dropfile { signalText0 signalText0.desc signalTextR signalTextR.desc }
dropfile { signalText1 signalText1.desc signalText2 signalText2.desc }
dropfile { signalText3 signalText3.desc signalText4 signalText4.desc }
dropfile { signalText5 signalText5.desc signalText6 signalText6.desc }
quit
