echo SLIDING
open sliding
descc
list 6

echo SPELLING
open spelling
descc
list 6

echo SHIFTED
open shifted
descc
list 5

echo SINGLE
open single
descc
list 7

echo REF_ELEM
open ref_elem
descc
list 7

echo ELEM2
open elem2
descc
list 5

echo EXPR
open expr
descc
list 5

echo EXPR1
open expr1
descc
list 6

echo COMPOSED
open composed
descc
list 6

echo NULLFIX
open nullfix
descc
list 5

echo NULLWIN
open nullwin
descc
list 5

echo REF_SINGLE
open ref_single
descc
list 7

echo REF_SUM
open ref_sum
descc
list 7

echo SCALAR3
open scalar3
descc
list 5

echo DERIVED3
open derived3
descc
list 5

echo CASTED
open casted
descc
list 6

quit
