@startuml


participant  Client
Entity       Payload
participant  Rdb
Entity       Description
database     Storage

== Create connection ==

Client -> Rdb : DataStorageAccessor()
Activate Rdb
Rdb -> Rdb: Open data file
Activate Description
Rdb -> Description : Fetch .desc file
Rdb -> Rdb : create FileAccessor()
Client -> Payload: Create payload area
deactivate Rdb
Activate Payload

== Read data ==

Client -> Rdb : Get()
Activate Rdb
Description -> Rdb : Get Size of Payload
Rdb -> Storage : FileAccessor.Read()
Storage --> Payload : Read data from disk
Rdb --> Client : Status
deactivate Rdb
Payload --> Client : Read payload area


== Write data ==

Client --> Payload: Fill Payload with Data
Client -> Rdb: Put()
Activate Rdb
Description -> Rdb : Get Size of Payload
Rdb -> Storage : FileAccessor.Write()
Payload -> Storage: Write data to disk
Rdb --> Client : Status
deactivate Rdb

@enduml