@startuml

title Storage Accessor - Activty Diagram


start

partition "construct" {
:storageAccessor(filename,[descriptorParam]) ;
note right: Crete storageAccessor class instance;

:assume descriptor as filename.desc;
}

partition "attachDescriptor" {
if (descriptor file exists?) then (yes)
  :read descriptor file;
  if (descriptorParam.has_not_value() ||
      descriptor == descriptorParam) then (yes)
    :set storage location
    [ref];
    note right: CurrDir if no ref;
  else (no)
    :<color:red>ERROR - differnet descriptors;
    stop
  endif
else (no)
	if (descriptorParam.has_value()) then (yes)
  :create descriptor file
  [ref];
  note right: CurrDir if no ref;
  else(no)
     :<color:red>ERROR - no descriptor;
    stop
  endif
endif

:<color:green>descriptor is ready;

note left: Storage location estabilished
}

partition "attachStorage" {
if (storage file exists?) then (yes)
  :attach storage;
  note left: compute storage size
else (no)
  :create storage;
endif

:<color:green>storage is ready;
}

:<color:green>attach payload;

stop

@enduml
