@startuml

participant  Client #Application
Entity       Payload #Lime
participant  Rdb #Lime
Entity       Description #Lime
database     Storage #Tomato

== Create connection ==

Client -> Rdb : storageAccessor() 
Activate Rdb #Lime
Rdb -> Rdb: Open data file
Activate Description #Lime
Rdb -> Description : Fetch .desc file
Rdb -> Rdb : create FileAccessor()
Client -> Payload: Create payload area
deactivate Rdb
Activate Payload #Lime

== Read data ==

Client -> Rdb : get()
Activate Rdb #Lime
Description --> Rdb : Get Size of Payload
Rdb -> Storage : FileAccessor.read()
Storage --> Payload : Read data from disk
Rdb --> Client : Status
deactivate Rdb
Payload --> Client : Read payload area


== Write data ==

Client -> Payload: Fill Payload area
Client -> Rdb: put()
Activate Rdb #Lime
Description --> Rdb : Get Size of Payload
Rdb -> Storage : FileAccessor.write()
Payload -> Storage: Write data to disk
Rdb --> Client : Status
deactivate Rdb

@enduml
