@startuml

title Storage Accessor - Activty Diagram


start

partition "construct" {
:storageAccessor(filename,[descriptorParam]) ;
note right: Crete storageAccessor class instance

:assume descriptor as filename.desc;
}

partition "attachDescriptor" {
if (descriptor file exists?) then (yes)
  :read descriptor file;
  if (descriptorParam.has_value() && descriptor == descriptorParam) then (yes)
    if (descriptor has ref?) then (yes)
      :storage location from ref;
    else (no)
      :default storage ref;
    endif
  else (no)
    :<color:red>ERROR - differnet descriptors;
    stop
  endif
else (no)
  :default storage ref;
  :create and store
  descriptor file;
endif

:<color:green>descriptor is ready;
}

partition "attachStorage" {
if (storage file exists?) then (yes)
  :attach storage;
  note left: compute storage size
else (no)
  :create storage;
endif

:<color:green>storage is ready;
}

:<color:green>attach payload;

stop

@enduml
