noprompt

echo serial1
open serial1
size
descc
list 6

echo serial2
open serial2
size
descc
list 6

echo serial3
open serial3
size
descc
list 6

echo serial7
open serial7
size
descc
list 6

echo serial8
open serial8
size
descc
list 6

dropfile { serial1 serial1.desc }
dropfile { serial2 serial2.desc }
dropfile { serial3 serial3.desc }
dropfile { serial7 serial7.desc }
dropfile { serial8 serial8.desc }

quit
