// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: supervisor.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Supervisor_Health_FullMethodName          = "/supervisor.v1.Supervisor/Health"
	Supervisor_ListQueries_FullMethodName     = "/supervisor.v1.Supervisor/ListQueries"
	Supervisor_GetQueryTree_FullMethodName    = "/supervisor.v1.Supervisor/GetQueryTree"
	Supervisor_Reload_FullMethodName          = "/supervisor.v1.Supervisor/Reload"
	Supervisor_UploadRQL_FullMethodName       = "/supervisor.v1.Supervisor/UploadRQL"
	Supervisor_Adhoc_FullMethodName           = "/supervisor.v1.Supervisor/Adhoc"
	Supervisor_StopRetractor_FullMethodName   = "/supervisor.v1.Supervisor/StopRetractor"
	Supervisor_Shutdown_FullMethodName        = "/supervisor.v1.Supervisor/Shutdown"
	Supervisor_GetLogs_FullMethodName         = "/supervisor.v1.Supervisor/GetLogs"
	Supervisor_StreamData_FullMethodName      = "/supervisor.v1.Supervisor/StreamData"
	Supervisor_GetStreamSchema_FullMethodName = "/supervisor.v1.Supervisor/GetStreamSchema"
)

// SupervisorClient is the client API for Supervisor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SupervisorClient interface {
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	ListQueries(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TextResponse, error)
	GetQueryTree(ctx context.Context, in *QueryTreeRequest, opts ...grpc.CallOption) (*TextResponse, error)
	Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	UploadRQL(ctx context.Context, in *UploadRQLRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Adhoc(ctx context.Context, in *AdhocRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	StopRetractor(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	GetLogs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LogsResponse, error)
	StreamData(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error)
	GetStreamSchema(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*SchemaResponse, error)
}

type supervisorClient struct {
	cc grpc.ClientConnInterface
}

func NewSupervisorClient(cc grpc.ClientConnInterface) SupervisorClient {
	return &supervisorClient{cc}
}

func (c *supervisorClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Supervisor_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorClient) ListQueries(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextResponse)
	err := c.cc.Invoke(ctx, Supervisor_ListQueries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorClient) GetQueryTree(ctx context.Context, in *QueryTreeRequest, opts ...grpc.CallOption) (*TextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextResponse)
	err := c.cc.Invoke(ctx, Supervisor_GetQueryTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorClient) Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Supervisor_Reload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorClient) UploadRQL(ctx context.Context, in *UploadRQLRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Supervisor_UploadRQL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorClient) Adhoc(ctx context.Context, in *AdhocRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Supervisor_Adhoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorClient) StopRetractor(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Supervisor_StopRetractor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Supervisor_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorClient) GetLogs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogsResponse)
	err := c.cc.Invoke(ctx, Supervisor_GetLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorClient) StreamData(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Supervisor_ServiceDesc.Streams[0], Supervisor_StreamData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, DataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Supervisor_StreamDataClient = grpc.ServerStreamingClient[DataChunk]

func (c *supervisorClient) GetStreamSchema(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*SchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchemaResponse)
	err := c.cc.Invoke(ctx, Supervisor_GetStreamSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupervisorServer is the server API for Supervisor service.
// All implementations must embed UnimplementedSupervisorServer
// for forward compatibility.
type SupervisorServer interface {
	Health(context.Context, *Empty) (*HealthResponse, error)
	ListQueries(context.Context, *Empty) (*TextResponse, error)
	GetQueryTree(context.Context, *QueryTreeRequest) (*TextResponse, error)
	Reload(context.Context, *ReloadRequest) (*StatusResponse, error)
	UploadRQL(context.Context, *UploadRQLRequest) (*StatusResponse, error)
	Adhoc(context.Context, *AdhocRequest) (*StatusResponse, error)
	StopRetractor(context.Context, *Empty) (*StatusResponse, error)
	Shutdown(context.Context, *Empty) (*StatusResponse, error)
	GetLogs(context.Context, *Empty) (*LogsResponse, error)
	StreamData(*StreamRequest, grpc.ServerStreamingServer[DataChunk]) error
	GetStreamSchema(context.Context, *StreamRequest) (*SchemaResponse, error)
	mustEmbedUnimplementedSupervisorServer()
}

// UnimplementedSupervisorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSupervisorServer struct{}

func (UnimplementedSupervisorServer) Health(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSupervisorServer) ListQueries(context.Context, *Empty) (*TextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListQueries not implemented")
}
func (UnimplementedSupervisorServer) GetQueryTree(context.Context, *QueryTreeRequest) (*TextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQueryTree not implemented")
}
func (UnimplementedSupervisorServer) Reload(context.Context, *ReloadRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedSupervisorServer) UploadRQL(context.Context, *UploadRQLRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadRQL not implemented")
}
func (UnimplementedSupervisorServer) Adhoc(context.Context, *AdhocRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Adhoc not implemented")
}
func (UnimplementedSupervisorServer) StopRetractor(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRetractor not implemented")
}
func (UnimplementedSupervisorServer) Shutdown(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedSupervisorServer) GetLogs(context.Context, *Empty) (*LogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedSupervisorServer) StreamData(*StreamRequest, grpc.ServerStreamingServer[DataChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamData not implemented")
}
func (UnimplementedSupervisorServer) GetStreamSchema(context.Context, *StreamRequest) (*SchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStreamSchema not implemented")
}
func (UnimplementedSupervisorServer) mustEmbedUnimplementedSupervisorServer() {}
func (UnimplementedSupervisorServer) testEmbeddedByValue()                    {}

// UnsafeSupervisorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SupervisorServer will
// result in compilation errors.
type UnsafeSupervisorServer interface {
	mustEmbedUnimplementedSupervisorServer()
}

func RegisterSupervisorServer(s grpc.ServiceRegistrar, srv SupervisorServer) {
	// If the following call panics, it indicates UnimplementedSupervisorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Supervisor_ServiceDesc, srv)
}

func _Supervisor_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Supervisor_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supervisor_ListQueries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServer).ListQueries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Supervisor_ListQueries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServer).ListQueries(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supervisor_GetQueryTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServer).GetQueryTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Supervisor_GetQueryTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServer).GetQueryTree(ctx, req.(*QueryTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supervisor_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Supervisor_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServer).Reload(ctx, req.(*ReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supervisor_UploadRQL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRQLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServer).UploadRQL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Supervisor_UploadRQL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServer).UploadRQL(ctx, req.(*UploadRQLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supervisor_Adhoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdhocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServer).Adhoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Supervisor_Adhoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServer).Adhoc(ctx, req.(*AdhocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supervisor_StopRetractor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServer).StopRetractor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Supervisor_StopRetractor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServer).StopRetractor(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supervisor_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Supervisor_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supervisor_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Supervisor_GetLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServer).GetLogs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supervisor_StreamData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SupervisorServer).StreamData(m, &grpc.GenericServerStream[StreamRequest, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Supervisor_StreamDataServer = grpc.ServerStreamingServer[DataChunk]

func _Supervisor_GetStreamSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServer).GetStreamSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Supervisor_GetStreamSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServer).GetStreamSchema(ctx, req.(*StreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Supervisor_ServiceDesc is the grpc.ServiceDesc for Supervisor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Supervisor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "supervisor.v1.Supervisor",
	HandlerType: (*SupervisorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Supervisor_Health_Handler,
		},
		{
			MethodName: "ListQueries",
			Handler:    _Supervisor_ListQueries_Handler,
		},
		{
			MethodName: "GetQueryTree",
			Handler:    _Supervisor_GetQueryTree_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _Supervisor_Reload_Handler,
		},
		{
			MethodName: "UploadRQL",
			Handler:    _Supervisor_UploadRQL_Handler,
		},
		{
			MethodName: "Adhoc",
			Handler:    _Supervisor_Adhoc_Handler,
		},
		{
			MethodName: "StopRetractor",
			Handler:    _Supervisor_StopRetractor_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Supervisor_Shutdown_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _Supervisor_GetLogs_Handler,
		},
		{
			MethodName: "GetStreamSchema",
			Handler:    _Supervisor_GetStreamSchema_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamData",
			Handler:       _Supervisor_StreamData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "supervisor.proto",
}
