noprompt
dropfile { test2 test2.desc }
open test2 { STRING name[5] INTEGER data[3] BYTE bt[3] BYTE Control FLOAT m1 INTEGER m2 }
size
set name test1
set data 1 2 3
set bt 1 2 3
set Control 2
set m1 1.23
set m2 234
append
printt
set name test2
set data 3 4 5
set bt 4 5 6
set Control 3
set m1 3.14
set m2 5567
append
read 0
printt
read 1
printt
size
echo list forward
list 2
echo list reverse
rlist 2
desc
input name test_1 data 6 9 3 bt 1 3 3 Control 2 m1 2.333 m2 264
printt
quitdrop
