#!/bin/bash

me="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

if [ $# -eq 0 ] ; then
    echo "Usage: $me queryFileName [PicType]"
    echo "Example: $me query"
    exit
fi

FILE=$1

if [ "$3" != "" ] ; then
PICTYPE=$2
else
PICTYPE=png
fi

arg=""

echo -e "Show fields?        [Y/n]\c"
read answer
if [ "$answer" == "${answer#[Nn]}" ] ;then
arg=$arg" -f"
fi

echo -e "Show stream progs?  [Y/n]\c"
read answer
if [ "$answer" == "${answer#[Nn]}" ] ;then
arg=$arg" -s"
fi

echo -e "Show tags?          [Y/n]\c"
read answer
if [ "$answer" == "${answer#[Nn]}" ] ;then
arg=$arg" -t"
fi

echo -e "Show types?         [Y/n]\c"
read answer
if [ "$answer" == "${answer#[Nn]}" ] ;then
arg=$arg" -w"
fi

echo 'Calling xretractor/dumper for '

if ! xretractor -c $FILE -d $arg > ${FILE%%.*}'.dot' ; then exit 1 ; fi

dot -T$PICTYPE ${FILE%%.*}'.dot' -o ${FILE%%.*}'.'$PICTYPE

rm ${FILE%%.*}'.dot'

#sudo apt install feh
feh ${FILE%%.*}'.'$PICTYPE

