# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: RetractorDB
email: michal@widera.com.pl
description: >- # this means to ignore newlines until "baseurl:"
  RetractorDB is an Time Series Database.
twitter_username: widera_michal
github_username:  michalwidera
minimal_mistakes_skin: default
search: true
logo: "/assets/images/icon/ms-icon-70x70.png"

url: "https://retractordb.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
timezone: Europe/Warsaw # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


## => Markdown Enhancements
##############################
## Mathjax
mathjax: true # false (default),
mathjax_autoNumber: true # false (default), true

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Michal Widera"
  avatar : "/assets/images/michal-photo.jpg"
  bio    : "Software engineer"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/widera_michal"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/michalwidera"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/michalwidera/"
    - label: "Homepage"
      icon: "fas fa-fw fa-link"
      url: "https://widera.com.pl"


footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/widera_michal"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/michalwidera/retractordb"
    - label: "Trademark"
      icon: "fa fa-trademark"
      url: "https://retractordb.com/trademark"
    - label: "Homepage"
      icon: "fas fa-fw fa-link"
      url: "https://widera.com.pl"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/
