# _Test description_
# testing binary data source as stream input
# reads datafile99.dat file and gets
# sequential results in loop
# notice: last $96 byte in overleaing intentionaly
noprompt
dropfile { data_source.desc }
open data_source { INTEGER dane REF "datafile99.dat" TYPE DEVICE }
desc
size
read 0
printt
read 0
printt
read 0
printt
read 0
printt
read 0
printt
read 0
printt
read 0
printt
read 0
printt
read 0
printt
read 0
printt
read 0
printt
dropfile { data_source.desc }
quit
